=head1 Perl Icons

This repo contains SVG images of icons associated with the Perl programming language. Because they are SVG, the icons can be easily embedded in a font icon file and used as Glyphs on a web page.

I'm licensing the icons under the FreeBSD license but be aware that the icons themselves may be subject to additional restrictions on use:

=over 4

=item * Camelia Perl 6 logo

This logo is copyright Larry Wall 2009. See L<details|https://raw.githubusercontent.com/perl6/mu/master/misc/camelia.txt>

=item * Perl and Camels

O'Reilly has a registered trademark on the camel and its association with Perl. See L<details|http://www.onlamp.com/pub/a/oreilly/perl/usage/>

=item * The Perl Onion

The Perl Foundation owns the Perl Onion logo and places certain restrictions on its use. See L<details|http://www.perlfoundation.org/perl_trademark>

=back 


=head2 Author

David Farrell


=head2 License

FreeBSD - see LICENSE

=cut